package Libre::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'Saveh::Schema',
    
    connect_info => {
        dsn => 'dbi:Pg:dbname=libre_dev;host=localhost',
        user => 'postgres',
        password => 'trustable',
        quote_names => q{1},
    }
);

=head1 NAME

Libre::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Libre>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Saveh::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.65

=head1 AUTHOR

junior

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
